### PR TITLE
allow concurrent serialisation of json

### PR DESCRIPTION
**Pull request by mvkra**
A small oversight in the memorisation code I introduced earlier. Without this JSON serialisation can break when working in parallel since the current code uses a Dictionary to cache data.

### CODE REVIEW

**Comment by mvkra** [comment]
Yep was just waiting on the AppVeyor build; I'm using 'dotnet test' so somewhat of a different test setup. Will dig into it.

**Comment by mvkra** [comment]
Ok - I think there might have been a change on the AppVeyor box since the last build? Not sure how that setup is provisioned. I'm seeing these errors in the log - note they don't relate to the code that was changed. Most FSharp projects usually bring FSharp.Core as a package an add binding redirects to fix this issue rather than use FSharp.Core directly from the GAC. If your OK with this change I can add it to the PR?

```
Error Message:
 Test method Microsoft.FSharpLu.Json.Tests+JsonSerializerTests.Fuzzing Reciprocal Compact threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at FsCheck.Config.get_VerboseThrowOnFailure()
   at FsCheck.Check.VerboseThrowOnFailureAll[Test]()
```

**Comment by blumu** [comment]
@mvkra The proposed fix sounds good. Thanks for taking care of this!

**Comment by mvkra** [comment]
Nice. If your happy with the change will leave it to you to merge (because I can't/no permissions on repo) and push the Nuget packge out.

**Comment by blumu** [comment]
This PR fixed bug #36

**Pull request merged**
